config/routes.rb
Rails.application.routes.draw do
  resources :cards do
    resources :billings
    collection { post :import }
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/billing.rb
class Billing < ApplicationRecord
	belongs_to :card
end

app/controllers/billings_controller.rb
class BillingsController < ApplicationController
	before_action :set_billing, only: [:show, :edit, :update, :destroy]

	def index
		@billings = Billing.all
	end

	def show
		@billing = Billing.find(params[:id])
	end

	def new
	@billing = Billing.new
	end

	def edit
		@billing = Billing.find(params[:id])
	end

	def create
		@billing = Billing.find(params[:id])
		@billing.save
		redirect_to billings_path
	end

	def update
		@billing = Billing.find(params[:id])
	end

	def destroy
		@billing.destroy
	end

	private
		def set_billing
			@billing = Billing.find(params[:id])
		end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/views/billings/_form.html.erb
<%= form_with(model: billing) do |form| %>
  <% if billing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(billing.errors.count, "error") %> prohibited this billing from being saved:</h2>

      <ul>
        <% billing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :card_holder_name %>
    <%= form.text_field :card_holder_name %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.number_field :card_number %>
  </div>

  <div class="field">
    <%= form.label :cvv_number %>
    <%= form.number_field :cvv_number %>
  </div>

  <div class="field">
    <%= form.label :valid_from %>
    <%= form.date_select :valid_from %>
  </div>

  <div class="field">
    <%= form.label :valid_upto %>
    <%= form.date_select :valid_upto %>
  </div>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.number_field :card_id %>
  </div>

  <div class="field">
    <%= form.label :card_type %>
    <%= form.text_field :card_type %>
  </div>

  <div class="field">
    <%= form.label :bank_name %>
    <%= form.text_field :bank_name %>
  </div>

  <div class="field">
    <%= form.label :total_amount %>
    <%= form.number_field :total_amount %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.number_field :paid_amount %>
  </div>

  <div class="field">
    <%= form.label :due_amount %>
    <%= form.number_field :due_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/billings/edit.html.erb
<h1>Editing Billing</h1>

<%= render 'form', billing: @billing %>

<%= link_to 'Back', billings_path %>

app/views/billings/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
    <h1>Billings Details</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Card Holder Name</th>
            <th>Card Number</th>
            <th>Cvv Number</th>
            <th>Valid From</th>
            <th>Valid Upto</th>
            <th>Card Id</th>
            <th>Card Type</th>
            <th>Bank Name</th>
            <th>Total Amount</th>
            <th>Paid Amount</th>
            <th>Due Amount</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      </table>
      <div>
        <%= link_to 'Back', cards_path() %>
      </div>
</div>

app/views/billings/new.html.erb
<h1>New Billing</h1>

<%= render 'form', billing: @billing %>

<%= link_to 'Back', root_path %>

app/views/billings/show.html.erb
<p>
  <strong>Card Holder Name:</strong>
  <%= @billing.card_holder_name %>
</p>

<p>
  <strong>Card Number:</strong>
  <%= @billing.card_number %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @billing.cvv_number %>
</p>

<p>
  <strong>Valid From:</strong>
  <%= @billing.valid_from %>
</p>

<p>
  <strong>Valid Upto:</strong>
  <%= @billing.valid_upto %>
</p>

<p>
  <strong>Card Id:</strong>
  <%= @billing.card_id %>
</p>

<p>
  <strong>Card Type:</strong>
  <%= @billing.card_type %>
</p>

<p>
  <strong>Bank Name:</strong>
  <%= @billing.bank_name %>
</p>


<p>
  <strong>Total Amount:</strong>
  <%= @billing.total_amount %>
</p>

<p>
  <strong>Paid Amount:</strong>
  <%= @billing.paid_amount %>
</p>

<p>
  <strong>Due Amount:</strong>
  <%= @billing.due_amount %>
</p>

 