config/routes.rb
Rails.application.routes.draw do
  resources :cards do
    resources :billings
    collection { post :import }
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :user
	has_many :billings

	enum card_type: [ :debit, :credit ]

	def self.to_csv(fields = column_names, options = {})
		CSV.generate(options) do |csv|
			csv << fields
			all.each do |card|
				csv << card.attributes.values_at(*fields)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			card_hash = row.to_hash
			card = create(card_holder_name: card_hash['card_holder_name'], card_number: card_hash['card_number'], cvv_number: card_hash['cvv_number'], valid_from: card_hash['valid_from'], valid_upto: card_hash['valid_upto'], user_id: card_hash['user_id'], card_type: card_hash['card_type'], bank_name: card_hash['bank_name'])			
		end
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :set_card, only: [:show, :edit, :update, :destroy]

	def index
		@cards = Card.all
		# @cards = Card.all.where(card_type: params[:card_type])
		respond_to do |format|
			format.html
			format.csv { send_data @cards.to_csv(['card_holder_name', 'card_number', 'cvv_number', 'valid_from', 'valid_upto', 'user_id', 'card_type', 'bank_name'])}
			format.json { render json: CardDatatable.new(params, view_context: view_context) }
		end
	end

	def import
		Card.import(params[:file])
		redirect_to cards_path, notice: "Cards imported"
	end

	def show
		@card = Card.find(params[:id])
	end

	def new
		@card = Card.new
	end

	def edit
		@card = Card.find(params[:id])
	end

	def create
		@card = Card.new(card_params)
		@card.save
		CrudNotificationMailer.create_notification(@card).deliver_now
		redirect_to cards_path
	end

	def update
		@card = Card.find(params[:id])
		@card.update(card_params)
		CrudNotificationMailer.update_notification(@card).deliver_now
		redirect_to cards_path
	end

	def destroy
		@card = Card.find(params[:id])
		CrudNotificationMailer.delete_notification(@card).deliver_now
		@card.destroy
		redirect_to cards_path
	end

	private
	  def set_card
      @card = Card.find(params[:id])
    end

		def card_params
	    params.require(:card).permit(:card_holder_name, :card_number, :cvv_number, :valid_from, :valid_upto, :user_id, :card_type, :bank_name).merge(user: current_user)
	  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :card_holder_name %>
    <%= form.text_field :card_holder_name %>
  </div>

  <div class="field">
    <%= form.label :card_number %>
    <%= form.text_field :card_number %>
  </div>

  <div class="field">
    <%= form.label :cvv_number %>
    <%= form.number_field :cvv_number %>
  </div>

  <div class="field">
    <%= form.label :valid_from %>
    <%= form.date_select :valid_from %>
  </div>

  <div class="field">
    <%= form.label :valid_upto %>
    <%= form.date_select :valid_upto %>
  </div>

  <div class="field">
    <%= form.label :bank_name %>
    <%= form.text_field :bank_name %>
  </div>
    
  <div class="field">
    <%= form.select(:card_type, ['debit', 'credit'])%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %>
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<div class="container">
	<br>
	<%= form_tag import_cards_path, multipart: true, class: 'form-inline' do %>
		<div class="form-group">
			<%= link_to "Export CSV", cards_path(format: :csv), class: 'btn btn-outline-primary' %>
		</div>

		<div class="form-group ml-3">
			<%= file_field_tag :file, class: 'btn btn-outline-warning btn-sm mr-3' %>
		</div>

		<div class="form-group">
			<%= submit_tag "Import CSV", class: 'btn btn-outline-info' %>
		</div>
  <% end %>
  <p id="notice"><%= notice %></p>
  <h1>Cards Details</h1>
	<br><br>
	<%= line_chart Card.group(:card_type).count %>
	<br><br>
	<table id="cards-datatable" class="table" data-source="<%= cards_path(format: :json, 
		card_type: params[:card_type]) %>">
	  <thead>
	    <tr>
	      <th>Card Holder Name</th>
	      <th>Card Number</th>
	      <th>Cvv Number</th>
	      <th>Valid From</th>
	      <th>Valid Upto</th>
	      <th>User Id</th>
	      <th>Card Type</th>
	      <th>Bank Name</th>
	    </tr>
	  </thead>
	  <tbody>
	  </tbody>
	</table>
	<div>
		<%= link_to 'New Card', new_card_path %> |
		<%= link_to 'Back', root_path %>
	</div>
</div>

<script>

// users.js

jQuery(document).ready(function() {
  $('#cards-datatable').dataTable({
    "processing": true,
    "serverSide": true,
    "ajax": {
      "url": $('#cards-datatable').data('source')
    },
    "pagingType": "full_numbers",
    "columns": [
      {"data": "card_holder_name"},
      {"data": "card_number"},
      {"data": "cvv_number"},
      {"data": "valid_from"},
      {"data": "valid_upto"},
      {"data": "user_id"},
      {"data": "card_type"},
      {"data": "bank_name"},

    ]
    // pagingType is optional, if you want full pagination controls.
    // Check dataTables documentation to learn more about
    // available options.
  });
});

</script>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p>
  <strong>Card Holder Name:</strong>
  <%= @card.card_holder_name %>
</p>
<p>
  <strong>Card Number:</strong>
  <%= @card.card_number.to_s.gsub!(/\d(?=[0-9]{4})/, '*') %>
</p>

<p>
  <strong>Cvv Number:</strong>
 <%= @card.cvv_number.to_s.gsub(/\d(?=[0-3]{0})/, '*') %>
</p>

<p>
  <strong>Valid From:</strong>
  <%= @card.valid_from%>
</p>

<p>
  <strong>Valid Upto:</strong>
  <%= @card.valid_upto %>
</p>

<p>
  <strong>User Id:</strong>
  <%= @card.user_id %>
</p>

<p>
  <strong>Card Type:</strong>
  <%= @card.card_type %>
</p>

<p>
  <strong>Bank Name:</strong>
  <%= @card.bank_name %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %>
<%= link_to 'Back', cards_path %>
<%= link_to 'Delete', @card, method: :delete, data: { confirm: 'Are you sure'} %>